source 'http://rubygems.org'

gem 'rake', '0.9.2'
gem 'unicorn', '3.6.2'
gem 'rails', '3.0.11'
gem 'bcrypt-ruby', :require => 'bcrypt'
gem 'rdiscount'
gem 'will_paginate', '3.0.pre2'
gem 'friendly_id', '3.3.0.1'
gem 'russian', '0.6.0'
gem 'mysql2', '0.2.6'
