social_profiles:
  github: 'http://github.com/rezwyi'
  twitter: 'http://twitter.com/rezwyi'
  facebook: 'http://facebook.com/rezwyigeek'
  linkedin: 'http://ru.linkedin.com/in/rezwyi'
  flickr: 'http://flickr.com/photos/rezwyi'
